from pandas_datareader import data as pdr
import yfinance as yf 
import os
import pandas as pd

iron = ["2S","A","ABICO","ACAP","ADAM","ADVANC","AEC","AEONTS","AF","AGE","AHC","AI","AIE","AIRA","AIT","AKP","AKR","ALT","AMA","AMANAH","AMATA","AMATAV","AMC","ANAN","AP","APCO","AQ","ARIP","ARROW","ASK","ASN","ASP","ATP30","AU","AUCT","AYUD","BAFS","BANPU","BAY","BBL","BCH","BCP","BCPG","BDMS","BFIT","BGT","BH","BIZ","BKD","BKI","BLA","BLAND","BLISS","BM","BOL","BPP","BROCK","BROOK","BSBM","BSM","BTW","BUI","CCN","CCP","CEN","CGD","CGH","CHARAN","CHEWA","CHG","CHO","CHOW","CHUO","CI","CIG","CIMBT","CITY","CKP","CMO","CMR","CNS","COLOR","COMAN","CPN","CPR","CSL","CSP","DAII","DCC","DCON","DCORP","DEMCO","DIMET","DNA","DRT","DTAC","EA","EARTH","EASTW","ECF","ECL","EFORL","EGCO","EKH","EPG","ESSO","ESTAR","EVER","FC","FER","FNS","FOCUS","FORTH","FPI","FSMART","FSS","FVC","GBX","GCAP","GEL","GJS","GL","GLAND","GLOW","GOLD","GPSC","GSTEL","GTB","GUNKUL","HARN","HOTPOT","HPT","HTECH","HYDRO","IEC","IFEC","IFS","ILINK","INET","INOX","INSURE","INTUCH","IRCP","IRPC","ITEL","J","JAS","JMART","JMT","JSP","JTS","JUBILE","K","KASET","KBANK","KC","KCAR","KCM","KDH","KGI","KIAT","KKP","KOOL","KTB","KTC","KWG","LALIN","LANNA","LDC","LH","LHBANK","LHK","LIT","LPH","LPN","LVT","M-CHAI","MAX","MBAX","MBK","MBKET","MCS","MDX","MFC","MFEC","MILL","MJD","MK","ML","e","MPG","MSC","MTI","MTLS","NBC","NCH","NCL","NDR","NETBAY","NEW","NEWS","NINE","NKI","NNCL","NOBLE","NPK","NSI","NTV","NUSA","OCEAN","ORI","OTO","PACE","PAE","PAP","PCA","PDG","PE","PERM","PF","PHOL","PICO","PIMO","PJW","PL","PLAT","POLAR","PPM","PPP","PPS","PRECHA","PRIN","PRINC","PSH","PSTC","PT","PTG","PTT","PTTEP","Q-CON","QH","QLT","QTC","RAM","RATCH","RCI","RICH","RICHY","RJH","RML","ROJNA","RP","RPC","RWI","S","S11","SALEE","SAM","SAMART","SAMCO","SAMTEL","SANKO","SAWAD","SC","SCB","SCC","SCCC","SCG","SCI","SCN","SCP","SEAOIL","SELIC","SENA","SF","SGF","SGP","SIM","SIMAT","SIRI","SIS","SKR","SMART","SMIT","SMK","SOLAR","SPA","SPALI","SPCG","SPRC","SPVI","SR","SSI","SSSC","STAR","SUPER","SUSCO","SVH","SVOA","SWC","SYMC","SYNEX","T","TACC","TAE","TAKUNI","TAPAC","TASCO","TCAP","TCC","TCMC","TFD","TGCI","TGPRO","THANA","THANI","THCOM","THE","THRE","THREL","TIC","TICON","TIP","TISCO","TIW","TK","TM","TMB","TMC","TMI","TMILL","TMT","TMW","TNDT","TNH","TNITY","TNP","TOP","TPAC","TPCH","TPIPL","TRT","TRUE","TSE","TSF","TSI","TSTH","TTW","TUCC","TVD","TVI","TVT","TWP","TWZ","TYCN","U","UAC","UBIS","UEC","UKEM","UMI","UMS","UOBKH","UPA","UREKA","UV","UWC","VIBHA","VIH","VNG","VTE","WHA","WIIK","WIN","WINNER","XO","YUASA","ZMICO"]


for ticker in iron:
    data = yf.download(ticker+".BK", start="2021-01-01", end="2021-04-30")
    data.to_csv('./datasets/stocks/' + ticker +'.csv')
    print(data)

